name: build

on:
  push:
    tags:
      - '*'

jobs:
  build-rotateproxy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
          workdir: cmd/httpxUtilz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
