name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-httpxUtilz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --snapshot --rm-dist --release-notes=CHANGELOG.md --release-header=header.tpl --release-footer=footer.tpl
          workdir: cmd/httpxUtilz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
